name: Sync Upstream Java Subdirectory

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 2 * * *' # every day at 02:00 UTC 

env:
  UPSTREAM_REPO: 'material-foundation/material-color-utilities'
  UPSTREAM_BRANCH: 'main'
  TARGET_DIR: 'java/'
  SYNC_BRANCH_NAME: sync-upstream-java
  PR_TARGET_BRANCH_NAME: main

jobs:
  validate-ref:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "${{ github.ref }}" != "refs/heads/${{ env.PR_TARGET_BRANCH_NAME }}" ]; then 
            echo "Can only be run for branch ${{ env.PR_TARGET_BRANCH_NAME }}"
            exit 1
          fi

  sync-subdirectory:
    needs: 
      - validate-ref
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}
      branch_exists: ${{ steps.base_ref.outputs.branch_exists }}

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.PR_TARGET_BRANCH_NAME }}
          fetch-depth: 0 # fetch full repository history, required for common ancestor commit

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git
          git fetch upstream ${{ env.UPSTREAM_BRANCH }}

      - name: Determine base ref
        id: base_ref
        run: |
          if git ls-remote --exit-code --heads origin ${{ env.SYNC_BRANCH_NAME }}; then
            echo "Sync-Branch already exists. Diff against ${{ env.SYNC_BRANCH_NAME }}."
            git fetch origin ${{ env.SYNC_BRANCH_NAME }}
            echo "base_ref=origin/${{ env.SYNC_BRANCH_NAME }}" >> $GITHUB_OUTPUT
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Sync-Branch does not exist yet. Diff against PR target branch: ${{ env.PR_TARGET_BRANCH_NAME }}"
            echo "base_ref=origin/${{ env.PR_TARGET_BRANCH_NAME }}" >> $GITHUB_OUTPUT
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for upstream changes in Java subdirectory
        id: check_diff
        run: |
          BASE_REF=${{ steps.base_ref.outputs.base_ref }}

          CHANGES=$(git diff --name-only $BASE_REF...upstream/${{ env.UPSTREAM_BRANCH }} -- ${{ env.TARGET_DIR }})

          if [ -z "$CHANGES" ]; then
            echo "No new upstream changes found in '${{ env.TARGET_DIR }}'"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in '${{ env.TARGET_DIR }}'!"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Git config as github-actions
        if: steps.check_diff.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create sync branch and merge
        if: steps.check_diff.outputs.has_changes  == 'true'
        run: |
          git checkout -B ${{ env.SYNC_BRANCH_NAME }}
          git merge upstream/${{ env.UPSTREAM_BRANCH }} --no-commit --no-ff
          
          git commit -m "Merge upstream changes"
          git push --force origin ${{ env.SYNC_BRANCH_NAME }}

  create-pr:
    needs: 
      - sync-subdirectory
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Check for existing PR
        id: existing_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_COUNT=$(gh pr list --head ${{ env.SYNC_BRANCH_NAME }} --state open --json number --jq 'length')
          if [ "$PR_COUNT" -eq "0" ]; then
            echo "No existing PR found for the branch ${{ env.SYNC_BRANCH_NAME }}."
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "Existing PR found for the branch ${{ env.SYNC_BRANCH_NAME }}."
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Check for differences to main
        id: branch_diff
        if: steps.existing_pr.outputs.exists == 'false' && needs.sync-subdirectory.outputs.branch_exists == 'true'
        run: |
          git fetch origin ${{ env.PR_TARGET_BRANCH_NAME }}
          git fetch origin ${{ env.SYNC_BRANCH_NAME }}
          
          CHANGES=$(git diff origin/${{ env.PR_TARGET_BRANCH_NAME }}..origin/${{ env.SYNC_BRANCH_NAME }} --name-only)

          if [ -z "$CHANGES" ]; then
            echo "Branch '${{ env.SYNC_BRANCH_NAME }}' is identical to '${{ env.PR_TARGET_BRANCH_NAME }}'."
            echo "has_diff=false" >> $GITHUB_OUTPUT
          else
            echo "Branch '${{ env.SYNC_BRANCH_NAME }}' has differences."
            echo "has_diff=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.existing_pr.outputs.exists == 'false' && (needs.sync-subdirectory.outputs.has_changes == 'true' || steps.branch_diff.outputs.has_diff == 'true')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base ${{ env.PR_TARGET_BRANCH_NAME }} \
            --head ${{ env.SYNC_BRANCH_NAME }} \
            --title "Sync: Updates in \`${{ env.TARGET_DIR }}\` from upstream" \
            --body "This automated PR syncs changes from the original upstream repository [${{ env.UPSTREAM_REPO }}](https://github.com/${{ env.UPSTREAM_REPO }})." \
            --assignee "Muckenbatscher" \
            --label "sync-upstream"
