name: Sync Upstream Java Subdirectory

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 2 * * *' # every day at 02:00 UTC 

env:
  UPSTREAM_REPO: 'material-foundation/material-color-utilities'
  UPSTREAM_BRANCH: 'main'
  TARGET_DIR: 'java/'
  SYNC_BRANCH_NAME: sync-upstream-java

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-subdirectory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git
          git fetch upstream ${{ env.UPSTREAM_BRANCH }}

      - name: Check for upstream changes in Java subdirectory
        id: check_diff
        run: |
          if git ls-remote --exit-code --heads origin ${{ env.SYNC_BRANCH_NAME }}; then
            echo "Sync-Branch already exists. Diff against ${{ env.SYNC_BRANCH_NAME }}."
            git fetch origin ${{ env.SYNC_BRANCH_NAME }}
            BASE_REF="origin/${{ env.SYNC_BRANCH_NAME }}"
          else
            echo "Sync-Branch does not exist yet. Diff against current HEAD."
            BASE_REF="HEAD"
          fi

          CHANGES=$(git diff --name-only $BASE_REF...upstream/${{ env.UPSTREAM_BRANCH }} -- ${{ env.TARGET_DIR }})

          if [ -z "$CHANGES" ]; then
            echo "No new upstream changes found in '${{ env.TARGET_DIR }}'"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in '${{ env.TARGET_DIR }}'!"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

          COMMON_SHA=$(git merge-base $BASE_REF upstream/${{ env.UPSTREAM_BRANCH }})
          echo "Most recent common ancestor commit: $COMMON_SHA"
          echo "common_sha=$COMMON_SHA" >> $GITHUB_OUTPUT

      - name: Set up Git config as github-actions
        if: steps.check_diff.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create sync branch and merge
        if: steps.check_diff.outputs.has_changes == 'true'
        run: |
          git checkout -B ${{ env.SYNC_BRANCH_NAME }}
          git merge upstream/${{ env.UPSTREAM_BRANCH }} --no-commit --no-ff

          echo "${{ steps.check_diff.outputs.common_sha }}" > .upstream-commit
          git add .upstream-commit
          
          git commit -m "Merge upstream changes and update .upstream-commit to ${{ steps.check_diff.outputs.common_sha }}"
          git push --force origin ${{ env.SYNC_BRANCH_NAME }}
          
      - name: Remove upstream remote
        run: git remote remove upstream
        
      - name: Check for existing PR
        if: steps.check_diff.outputs.has_changes == 'true'
        id: exsting_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_COUNT=$(gh pr list --head ${{ env.SYNC_BRANCH_NAME }} --state open --json number --jq 'length')
          if [ "$PR_COUNT" -eq "0" ]; then
            echo "No existing PR found for the branch ${{ env.SYNC_BRANCH_NAME }}."
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "Existing PR found for the branch ${{ env.SYNC_BRANCH_NAME }}."
            echo "exists=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.exsting_pr.outputs.exists != 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base ${{ github.ref_name }} \
            --head ${{ env.SYNC_BRANCH_NAME }} \
            --title "Sync: Updates in \`${{ env.TARGET_DIR }}\` from upstream" \
            --body "This automated PR syncs changes from the original upstream repository **${{ env.UPSTREAM_REPO }}**."
